server:
  port: 8081

spring:
  application:
    name: ORDER-SERVICE

  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create

ORDER-SERVICE:
  send-topics: token-validation-topic
  reply-topics: token-validation-topic-reply
  consumer-group: token-validation-group
  send-menu: get-menu-topic
  reply-menu: get-menu-topic-reply
  consumer-group-menu: get-menu-group

eureka:
  client:
    service-uri:
      defaultZone: http://localhost:8761/eureka/