spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/menu
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
menu:
  send-menu: get-menu-topic
  reply-menu: get-menu-topic-reply
  consumer-group-menu: get-menu-group
server:
  port: 8092